require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/repository_types", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # RepositoryType. As you add validations to RepositoryType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RepositoryType.create! valid_attributes
      get repository_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      repository_type = RepositoryType.create! valid_attributes
      get repository_type_url(repository_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_repository_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      repository_type = RepositoryType.create! valid_attributes
      get edit_repository_type_url(repository_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RepositoryType" do
        expect {
          post repository_types_url, params: { repository_type: valid_attributes }
        }.to change(RepositoryType, :count).by(1)
      end

      it "redirects to the created repository_type" do
        post repository_types_url, params: { repository_type: valid_attributes }
        expect(response).to redirect_to(repository_type_url(RepositoryType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RepositoryType" do
        expect {
          post repository_types_url, params: { repository_type: invalid_attributes }
        }.to change(RepositoryType, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post repository_types_url, params: { repository_type: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested repository_type" do
        repository_type = RepositoryType.create! valid_attributes
        patch repository_type_url(repository_type), params: { repository_type: new_attributes }
        repository_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the repository_type" do
        repository_type = RepositoryType.create! valid_attributes
        patch repository_type_url(repository_type), params: { repository_type: new_attributes }
        repository_type.reload
        expect(response).to redirect_to(repository_type_url(repository_type))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        repository_type = RepositoryType.create! valid_attributes
        patch repository_type_url(repository_type), params: { repository_type: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested repository_type" do
      repository_type = RepositoryType.create! valid_attributes
      expect {
        delete repository_type_url(repository_type)
      }.to change(RepositoryType, :count).by(-1)
    end

    it "redirects to the repository_types list" do
      repository_type = RepositoryType.create! valid_attributes
      delete repository_type_url(repository_type)
      expect(response).to redirect_to(repository_types_url)
    end
  end
end
